version: '2'

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: php-code
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    links:
      - db
    ports:
      - '8111:80'
    network_mode: bridge

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    volumes:
      - mysqlcode:/var/lib/mysql
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    network_mode: bridge

#  tests:
#    image: "lehrermarktplatz/php-dev-test:latest"
#    command: [ "-s", "basic" ]
#    network_mode: bridge
#    environment:
#      APP_HOST: "php"
#      APP_PORT: "80"


volumes:
  mysqlcode:
